name: appbanco_bbva_ventas
description: "BBVA Fuerza de Ventas — App Móvil para Ejecutivos de Negocio"
publish_to: "none"
version: 2.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.0.0

  # Backend
  supabase_flutter: ^2.8.4

  # Local Storage
  sqflite: ^2.3.3
  path: ^1.9.0
  flutter_secure_storage: ^9.2.2

  # Maps & Location
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  url_launcher: ^6.2.6

  # Camera & Images
  camera: ^0.11.0
  image_picker: ^1.1.2
  image: ^4.2.0

  # Charts
  fl_chart: ^0.68.0

  # Notifications
  flutter_local_notifications: ^17.2.2
  firebase_messaging: ^15.1.3
  workmanager: ^0.9.0

  # Signature
  signature: ^5.4.1

  # PDF
  pdf: ^3.11.1
  printing: ^5.13.2

  # Utilities
  intl: ^0.19.0
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bbva_logo.png
